### ISSUE TITLE
Precision of the distance to self

### ISSUE THREAD

**Issue by as6520** [Vastlab/vast#49]
I have been running into the assertion error present in https://github.com/Vastlab/vast/blob/main/vast/opensetAlgos/EVM.py#L247. Changing the precision to 1e-05 seems to fix the problem. I had 3 questions about it.

1. Why is this assertion required?
2. If it is known that the 1e-05 values can occur in this computation why is 1e-06 used?
3. While the suggestion is helpful, there is no good way to change this precision as a user of this library except to change it in code. If this assertion is required and precision of 1e-06 is required too, can it be added a parameter to the constructor so that a downstream agent can change the precision when the assertion is encountered?

**Comment by akshay-raj-dhamija** [comment]
I agree the assertion is not actually needed it was originally introduced for debugging purposes especially when changes were being made inside the `EVM_Training` function and the distance metrics. While I think it should be safe to remove it altogether, I would advocate for converting it into a warning message rather than raising an assertion so that in case someone does anything funky with a new distance metric they at least get a pointer to what might be wrong.
Would also set the default to `1e-5`.

**Comment by akshay-raj-dhamija** [comment]
The fix has been merged, please reopen if needed.
